name: Deploy Petstore API

on:
  push:
    branches: ["master"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to OpenShift
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          tar -xvzf openshift-client-linux.tar.gz
          chmod +x oc
          sudo mv oc /usr/local/bin/
          oc login $OPENSHIFT_SERVER --token=$OPENSHIFT_TOKEN

      - name: Build and push image
        run: |
          oc new-build --binary --name=petstore-api -l app=petstore-api --strategy=docker
          oc start-build petstore-api --from-dir=. --follow

      - name: Deploy to OpenShift
        run: |
          oc apply -f deployment-ocp.yaml
          oc expose deployment petstore-api
